# Generated by Django 4.1 on 2024-04-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem", old_name="produit", new_name="product",
        ),
    ]
