# Generated by Django 4.1 on 2024-04-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_produit_orderitem_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem", old_name="product", new_name="produit",
        ),
    ]
