# Generated by Django 4.1 on 2024-05-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_product_image_imagedetailproduct"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagedetailproduct",
            old_name="produit",
            new_name="produit_image",
        ),
    ]
